// ABOUTME: Generates editorial-quality images for Creative Studio system welcome cards
// ABOUTME: Reads prompts from studio_welcome_image_prompts table, supports Gemini and Imagen models

import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY")!;
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const BASE_URL = "https://generativelanguage.googleapis.com/v1beta";
const DEFAULT_MODEL = "gemini-3-pro-image-preview";

// ── Media registration helper ─────────────────────────────────────────────
// Inlined to avoid relative import issues at deploy time

type SupabaseClientType = ReturnType<typeof createClient>;

async function ensureFolderPath(
  supabase: SupabaseClientType,
  folderPath: string,
): Promise<string | null> {
  const segments = folderPath.split('/').filter(Boolean);
  if (segments.length === 0) return null;

  let parentId: string | null = null;
  let currentPath = '';

  for (const segment of segments) {
    currentPath += '/' + segment;
    const { data: existing } = await supabase
      .from('media_folders').select('id').eq('path', currentPath).single();

    if (existing) { parentId = existing.id; continue; }

    const { data: created, error } = await supabase
      .from('media_folders')
      .insert({ name: segment, path: currentPath, parent_id: parentId,
        description: parentId ? null : 'Images created by AI generators across the platform',
        color: '#8b5cf6', icon: parentId ? 'folder' : 'sparkles' })
      .select('id').single();

    if (created) {
      parentId = created.id;
    } else if (error) {
      const { data: raceWinner } = await supabase
        .from('media_folders').select('id').eq('path', currentPath).single();
      parentId = raceWinner?.id ?? null;
    }
  }
  return parentId;
}

async function registerMediaImage(supabase: SupabaseClientType, params: {
  url: string; storagePath: string; filename: string; mimeType: string;
  sizeBytes: number; folderPath: string; title?: string; description?: string;
  autoTags?: string[]; customMetadata?: Record<string, unknown>; modelUsed?: string;
}): Promise<void> {
  try {
    const folderId = await ensureFolderPath(supabase, params.folderPath);
    await supabase.from('media').insert({
      filename: params.filename, title: params.title || params.filename,
      description: params.description || null, url: params.url,
      storage_path: params.storagePath, thumbnail_url: params.url,
      mime_type: params.mimeType, file_type: 'image', size_bytes: params.sizeBytes,
      folder_id: folderId, created_by: null, auto_tags: params.autoTags || [],
      custom_metadata: { source: 'ai-generated', ...params.customMetadata },
      ...(params.modelUsed ? {
        synthid_detected: true, synthid_confidence: 1.0,
        synthid_generated_by: params.modelUsed,
        synthid_details: 'AI-generated by Vince Creative Studio',
      } : {}),
    });
  } catch (err) {
    console.error('[registerMediaImage] error:', err);
  }
}

// ── Image generation ──────────────────────────────────────────────────────

function isImagenModel(model: string): boolean {
  return model.startsWith("imagen");
}

async function generateImage(
  prompt: string,
  aspectRatio: string,
  model: string,
): Promise<string | null> {
  const isImagen = isImagenModel(model);
  const endpoint = isImagen
    ? `${BASE_URL}/models/${model}:predict`
    : `${BASE_URL}/models/${model}:generateContent`;

  const body = isImagen
    ? {
        instances: [{ prompt }],
        parameters: {
          sampleCount: 1,
          aspectRatio,
        },
      }
    : {
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          responseModalities: ["TEXT", "IMAGE"],
          imageConfig: { aspectRatio },
        },
      };

  const response = await fetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-goog-api-key": GEMINI_API_KEY,
    },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const errText = await response.text();
    console.error(`API error (${model}): ${response.status} — ${errText}`);
    return null;
  }

  const data = await response.json();

  if (isImagen) {
    const prediction = data?.predictions?.[0];
    if (prediction?.bytesBase64Encoded) {
      return prediction.bytesBase64Encoded;
    }
    console.error("No image data in Imagen response");
    return null;
  }

  // Gemini response
  const parts = data?.candidates?.[0]?.content?.parts;
  if (!parts) {
    console.error("No parts in Gemini response");
    return null;
  }

  for (const part of parts) {
    if (part.inlineData?.data) {
      return part.inlineData.data;
    }
  }

  console.error("No image data in response parts");
  return null;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    const { sections: requestedSections, model: requestedModel } = await req
      .json()
      .catch(() => ({ sections: null, model: null }));

    const model = requestedModel || DEFAULT_MODEL;

    // Read prompts from DB
    let query = supabase
      .from("studio_welcome_image_prompts")
      .select("image_key, label, prompt, aspect_ratio")
      .order("sort_order");

    if (requestedSections?.length) {
      query = query.in("image_key", requestedSections);
    }

    const { data: prompts, error: promptErr } = await query;

    if (promptErr || !prompts?.length) {
      return new Response(
        JSON.stringify({ error: promptErr?.message || "No prompts found" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const results: Record<string, { status: string; url?: string; error?: string }> = {};

    for (const row of prompts) {
      const { image_key, label, prompt, aspect_ratio } = row;

      console.log(`Generating ${image_key} (${label}) with ${model}...`);
      const startTime = Date.now();

      try {
        const base64 = await generateImage(prompt, aspect_ratio, model);
        if (!base64) {
          results[image_key] = { status: "failed", error: `No image from ${model}` };
          continue;
        }

        const generationTimeMs = Date.now() - startTime;

        const bytes = Uint8Array.from(atob(base64), (c) => c.charCodeAt(0));
        const filePath = `studio-welcome/${image_key}-${Date.now()}.png`;

        const { error: uploadErr } = await supabase.storage
          .from("media")
          .upload(filePath, bytes, {
            contentType: "image/png",
            upsert: false,
          });

        if (uploadErr) {
          results[image_key] = { status: "upload_failed", error: uploadErr.message };
          continue;
        }

        const { data: { publicUrl } } = supabase.storage
          .from("media")
          .getPublicUrl(filePath);

        // Track in ai_image_generations (correct table for UI history queries)
        await supabase.from("ai_image_generations").insert({
          user_id: null,
          prompt,
          original_prompt: `Studio welcome: ${label}`,
          model_used: model,
          status: "completed",
          image_url: publicUrl,
          storage_path: `media/${filePath}`,
          file_size: bytes.length,
          generation_time_ms: generationTimeMs,
          content_type: "studio-welcome",
          category: "studio-welcome",
          title: label,
          metadata: {
            sectionKey: image_key,
            aspectRatio: aspect_ratio,
            bulkGeneration: true,
          },
        });

        // Register in media library for discoverability
        await registerMediaImage(supabase, {
          url: publicUrl,
          storagePath: `media/${filePath}`,
          filename: `${image_key}-${Date.now()}.png`,
          mimeType: "image/png",
          sizeBytes: bytes.length,
          folderPath: "/AI Generated/Welcome",
          title: label,
          description: prompt.substring(0, 200),
          autoTags: ["ai-generated", "studio-welcome", image_key],
          customMetadata: {
            source: "studio-welcome-generator",
            sectionKey: image_key,
            model_used: model,
            aspectRatio: aspect_ratio,
          },
          modelUsed: model,
        });

        results[image_key] = { status: "success", url: publicUrl };
        console.log(`✓ ${image_key} → ${publicUrl} (${generationTimeMs}ms, ${model})`);

        // Persist progress immediately — each image saved as it completes.
        // Use SELECT→UPDATE/INSERT to avoid upsert creating duplicate rows.
        const { data: existingRow } = await supabase
          .from("site_settings")
          .select("id, value")
          .eq("key", "creative_studio_welcome_images")
          .maybeSingle();

        const merged = {
          ...((existingRow?.value as Record<string, string>) || {}),
          [image_key]: publicUrl,
        };

        if (existingRow?.id) {
          await supabase
            .from("site_settings")
            .update({ value: merged })
            .eq("id", existingRow.id);
        } else {
          await supabase
            .from("site_settings")
            .insert({ key: "creative_studio_welcome_images", value: merged, is_active: true });
        }
      } catch (err) {
        results[image_key] = { status: "error", error: String(err) };
      }
    }

    const successCount = Object.values(results).filter((r) => r.status === "success").length;
    const failCount = Object.values(results).filter((r) => r.status !== "success").length;

    return new Response(
      JSON.stringify({
        summary: { total: prompts.length, success: successCount, failed: failCount, model },
        results,
      }, null, 2),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (err) {
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
